spring.application.name=talents-express-api
server.port=8080

# H2 em memoria para testes locais sem PostgreSQL
# Para usar PostgreSQL: comente o bloco H2 e descomente o bloco PostgreSQL abaixo

spring.datasource.url=jdbc:h2:mem:talentsexpress;DB_CLOSE_DELAY=-1;NON_KEYWORDS=VALUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# # ---- PARA PRODUCAO (PostgreSQL) ----
# spring.datasource.url=jdbc:postgresql://localhost:5432/talents_express
# spring.datasource.username=postgres
# spring.datasource.password=postgres
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true
spring.jackson.serialization.fail-on-empty-beans=false

# JWT
app.jwt.secret=TalentsExpressSecretKey2026TalentsExpressSecretKey2026
app.jwt.expiration-ms=86400000

# CORS
app.cors.allowed-origins=*

logging.level.com.talentsexpress=DEBUG
